services:
  db:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./backend
    image: stock-backend
    command: >
      sh -c "python manage.py migrate &&
            #  python manage.py seed_companies &&
            #  python manage.py generate_company_embeddings &&
            #  python manage.py crawl_spider sharesansar_prices &&
            #  python manage.py crawl_spider sharesansar_news &&
             python manage.py categorize_news_by_embeddings &&
             uvicorn Stock.asgi:application --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend:/backend
      - /backend/.venv/
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  # celery-worker:
  #   build:
  #     context: ./backend
  #   image: stock-backend
  #   # 1. ADD THIS LINE:
  #   working_dir: /backend
  #   command: celery -A Stock worker -l info
  #   volumes:
  #     - ./backend:/backend
  #     - /backend/.venv/
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_HOST: db
  #     POSTGRES_PORT: 5432
  #     CELERY_BROKER_URL: redis://redis:6379/0
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy

  # celery-beat:
  #   build:
  #     context: ./backend
  #   image: stock-backend
  #   # 2. ADD THIS LINE:
  #   working_dir: /backend
  #   command: celery -A Stock beat -l info
  #   volumes:
  #     - ./backend:/backend
  #     - /backend/.venv/
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_HOST: db
  #     POSTGRES_PORT: 5432
  #     CELERY_BROKER_URL: redis://redis:6379/0
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy


  frontend:
    build:
      context: ./frontend
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules/
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - web

volumes:
  postgres_data:
