--
-- PostgreSQL database dump
--

\restrict tbf2HxWq3yTV2RvnvjWaSbADXbYiAs90n3RYzodmqkKWd3r8hBqtrdT0Ja3D0Ht

-- Dumped from database version 16.14 (Debian 16.14-1.pgdg12+1)
-- Dumped by pg_dump version 16.14 (Debian 16.14-1.pgdg12+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: analysis_behaviorsummary; Type: TABLE; Schema: public; Owner: nimesh
--

CREATE TABLE public.analysis_behaviorsummary (
    id bigint NOT NULL,
    date date NOT NULL,
    vwap numeric(12,2),
    close numeric(12,2) NOT NULL,
    pressure_indicator character varying(20) NOT NULL,
    is_volume_anomaly boolean NOT NULL,
    avg_volume_20d bigint,
    computed_at timestamp with time zone NOT NULL,
    company_id bigint NOT NULL
);


ALTER TABLE public.analysis_behaviorsummary OWNER TO nimesh;

--
-- Name: analysis_behaviorsummary_id_seq; Type: SEQUENCE; Schema: public; Owner: nimesh
--

ALTER TABLE public.analysis_behaviorsummary ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analysis_behaviorsummary_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: analysis_newspricecorrelation; Type: TABLE; Schema: public; Owner: nimesh
--

CREATE TABLE public.analysis_newspricecorrelation (
    id bigint NOT NULL,
    window_start date NOT NULL,
    window_end date NOT NULL,
    correlation_coefficient double precision NOT NULL,
    news_count integer NOT NULL,
    price_change_pct double precision NOT NULL,
    volume_change_pct double precision NOT NULL,
    computed_at timestamp with time zone NOT NULL,
    company_id bigint NOT NULL
);


ALTER TABLE public.analysis_newspricecorrelation OWNER TO nimesh;

--
-- Name: analysis_newspricecorrelation_id_seq; Type: SEQUENCE; Schema: public; Owner: nimesh
--

ALTER TABLE public.analysis_newspricecorrelation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analysis_newspricecorrelation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: nimesh
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO nimesh;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: nimesh
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: nimesh
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO nimesh;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: nimesh
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: nimesh
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO nimesh;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: nimesh
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: nimesh
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO nimesh;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: nimesh
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO nimesh;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: nimesh
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: nimesh
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: nimesh
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO nimesh;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: nimesh
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: nimesh
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO nimesh;

--
-- Name: companies_company; Type: TABLE; Schema: public; Owner: nimesh
--

CREATE TABLE public.companies_company (
    id bigint NOT NULL,
    symbol character varying(20) NOT NULL,
    name character varying(255) NOT NULL,
    sector character varying(100) NOT NULL,
    aliases jsonb NOT NULL,
    description text NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.companies_company OWNER TO nimesh;

--
-- Name: companies_company_id_seq; Type: SEQUENCE; Schema: public; Owner: nimesh
--

ALTER TABLE public.companies_company ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.companies_company_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: companies_companyembedding; Type: TABLE; Schema: public; Owner: nimesh
--

CREATE TABLE public.companies_companyembedding (
    id bigint NOT NULL,
    embedding public.vector(384) NOT NULL,
    source_text text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    company_id bigint NOT NULL
);


ALTER TABLE public.companies_companyembedding OWNER TO nimesh;

--
-- Name: companies_companyembedding_id_seq; Type: SEQUENCE; Schema: public; Owner: nimesh
--

ALTER TABLE public.companies_companyembedding ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.companies_companyembedding_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: companies_dailyprice; Type: TABLE; Schema: public; Owner: nimesh
--

CREATE TABLE public.companies_dailyprice (
    id bigint NOT NULL,
    date date NOT NULL,
    open numeric(12,2) NOT NULL,
    high numeric(12,2) NOT NULL,
    low numeric(12,2) NOT NULL,
    close numeric(12,2) NOT NULL,
    volume bigint NOT NULL,
    turnover numeric(16,2) NOT NULL,
    company_id bigint NOT NULL
);


ALTER TABLE public.companies_dailyprice OWNER TO nimesh;

--
-- Name: companies_dailyprice_id_seq; Type: SEQUENCE; Schema: public; Owner: nimesh
--

ALTER TABLE public.companies_dailyprice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.companies_dailyprice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: companies_floorsheettransaction; Type: TABLE; Schema: public; Owner: nimesh
--

CREATE TABLE public.companies_floorsheettransaction (
    id bigint NOT NULL,
    date date NOT NULL,
    buyer_broker character varying(100) NOT NULL,
    seller_broker character varying(100) NOT NULL,
    quantity integer NOT NULL,
    rate numeric(12,2) NOT NULL,
    company_id bigint NOT NULL
);


ALTER TABLE public.companies_floorsheettransaction OWNER TO nimesh;

--
-- Name: companies_floorsheettransaction_id_seq; Type: SEQUENCE; Schema: public; Owner: nimesh
--

ALTER TABLE public.companies_floorsheettransaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.companies_floorsheettransaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crawler_crawlrun; Type: TABLE; Schema: public; Owner: nimesh
--

CREATE TABLE public.crawler_crawlrun (
    id bigint NOT NULL,
    source character varying(50) NOT NULL,
    status character varying(20) NOT NULL,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    stats jsonb NOT NULL,
    triggered_by_id integer
);


ALTER TABLE public.crawler_crawlrun OWNER TO nimesh;

--
-- Name: crawler_crawlrun_id_seq; Type: SEQUENCE; Schema: public; Owner: nimesh
--

ALTER TABLE public.crawler_crawlrun ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crawler_crawlrun_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: nimesh
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO nimesh;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: nimesh
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: nimesh
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO nimesh;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: nimesh
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: nimesh
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO nimesh;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: nimesh
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: nimesh
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO nimesh;

--
-- Name: news_articlecategory; Type: TABLE; Schema: public; Owner: nimesh
--

CREATE TABLE public.news_articlecategory (
    id bigint NOT NULL,
    confidence double precision NOT NULL,
    method character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    company_id bigint NOT NULL,
    article_id bigint NOT NULL
);


ALTER TABLE public.news_articlecategory OWNER TO nimesh;

--
-- Name: news_articlecategory_id_seq; Type: SEQUENCE; Schema: public; Owner: nimesh
--

ALTER TABLE public.news_articlecategory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.news_articlecategory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: news_articleembedding; Type: TABLE; Schema: public; Owner: nimesh
--

CREATE TABLE public.news_articleembedding (
    id bigint NOT NULL,
    embedding public.vector(384) NOT NULL,
    source_text text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    article_id bigint NOT NULL
);


ALTER TABLE public.news_articleembedding OWNER TO nimesh;

--
-- Name: news_articleembedding_id_seq; Type: SEQUENCE; Schema: public; Owner: nimesh
--

ALTER TABLE public.news_articleembedding ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.news_articleembedding_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: news_categorycorrection; Type: TABLE; Schema: public; Owner: nimesh
--

CREATE TABLE public.news_categorycorrection (
    id bigint NOT NULL,
    reason text NOT NULL,
    corrected_at timestamp with time zone NOT NULL,
    article_category_id bigint NOT NULL,
    corrected_by_id integer,
    new_company_id bigint NOT NULL,
    previous_company_id bigint
);


ALTER TABLE public.news_categorycorrection OWNER TO nimesh;

--
-- Name: news_categorycorrection_id_seq; Type: SEQUENCE; Schema: public; Owner: nimesh
--

ALTER TABLE public.news_categorycorrection ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.news_categorycorrection_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: news_rawarticle; Type: TABLE; Schema: public; Owner: nimesh
--

CREATE TABLE public.news_rawarticle (
    id bigint NOT NULL,
    source_portal character varying(50) NOT NULL,
    headline character varying(500) NOT NULL,
    body text NOT NULL,
    url character varying(500) NOT NULL,
    published_at timestamp with time zone,
    scraped_at timestamp with time zone NOT NULL
);


ALTER TABLE public.news_rawarticle OWNER TO nimesh;

--
-- Name: news_rawarticle_id_seq; Type: SEQUENCE; Schema: public; Owner: nimesh
--

ALTER TABLE public.news_rawarticle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.news_rawarticle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: analysis_behaviorsummary analysis_behaviorsummary_company_id_date_d12d10de_uniq; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.analysis_behaviorsummary
    ADD CONSTRAINT analysis_behaviorsummary_company_id_date_d12d10de_uniq UNIQUE (company_id, date);


--
-- Name: analysis_behaviorsummary analysis_behaviorsummary_pkey; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.analysis_behaviorsummary
    ADD CONSTRAINT analysis_behaviorsummary_pkey PRIMARY KEY (id);


--
-- Name: analysis_newspricecorrelation analysis_newspricecorrelation_pkey; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.analysis_newspricecorrelation
    ADD CONSTRAINT analysis_newspricecorrelation_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: companies_company companies_company_pkey; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.companies_company
    ADD CONSTRAINT companies_company_pkey PRIMARY KEY (id);


--
-- Name: companies_company companies_company_symbol_key; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.companies_company
    ADD CONSTRAINT companies_company_symbol_key UNIQUE (symbol);


--
-- Name: companies_companyembedding companies_companyembedding_company_id_key; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.companies_companyembedding
    ADD CONSTRAINT companies_companyembedding_company_id_key UNIQUE (company_id);


--
-- Name: companies_companyembedding companies_companyembedding_pkey; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.companies_companyembedding
    ADD CONSTRAINT companies_companyembedding_pkey PRIMARY KEY (id);


--
-- Name: companies_dailyprice companies_dailyprice_company_id_date_5e2acbd6_uniq; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.companies_dailyprice
    ADD CONSTRAINT companies_dailyprice_company_id_date_5e2acbd6_uniq UNIQUE (company_id, date);


--
-- Name: companies_dailyprice companies_dailyprice_pkey; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.companies_dailyprice
    ADD CONSTRAINT companies_dailyprice_pkey PRIMARY KEY (id);


--
-- Name: companies_floorsheettransaction companies_floorsheettransaction_pkey; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.companies_floorsheettransaction
    ADD CONSTRAINT companies_floorsheettransaction_pkey PRIMARY KEY (id);


--
-- Name: crawler_crawlrun crawler_crawlrun_pkey; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.crawler_crawlrun
    ADD CONSTRAINT crawler_crawlrun_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: news_articlecategory news_articlecategory_pkey; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.news_articlecategory
    ADD CONSTRAINT news_articlecategory_pkey PRIMARY KEY (id);


--
-- Name: news_articleembedding news_articleembedding_article_id_key; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.news_articleembedding
    ADD CONSTRAINT news_articleembedding_article_id_key UNIQUE (article_id);


--
-- Name: news_articleembedding news_articleembedding_pkey; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.news_articleembedding
    ADD CONSTRAINT news_articleembedding_pkey PRIMARY KEY (id);


--
-- Name: news_categorycorrection news_categorycorrection_pkey; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.news_categorycorrection
    ADD CONSTRAINT news_categorycorrection_pkey PRIMARY KEY (id);


--
-- Name: news_rawarticle news_rawarticle_pkey; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.news_rawarticle
    ADD CONSTRAINT news_rawarticle_pkey PRIMARY KEY (id);


--
-- Name: news_rawarticle news_rawarticle_url_key; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.news_rawarticle
    ADD CONSTRAINT news_rawarticle_url_key UNIQUE (url);


--
-- Name: news_articlecategory unique_article_company_category; Type: CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.news_articlecategory
    ADD CONSTRAINT unique_article_company_category UNIQUE (article_id, company_id);


--
-- Name: analysis_behaviorsummary_company_id_ac7ed932; Type: INDEX; Schema: public; Owner: nimesh
--

CREATE INDEX analysis_behaviorsummary_company_id_ac7ed932 ON public.analysis_behaviorsummary USING btree (company_id);


--
-- Name: analysis_newspricecorrelation_company_id_40723770; Type: INDEX; Schema: public; Owner: nimesh
--

CREATE INDEX analysis_newspricecorrelation_company_id_40723770 ON public.analysis_newspricecorrelation USING btree (company_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: nimesh
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: nimesh
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: nimesh
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: nimesh
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: nimesh
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: nimesh
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: nimesh
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: nimesh
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: nimesh
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: nimesh
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: companies_company_symbol_9f158f8c_like; Type: INDEX; Schema: public; Owner: nimesh
--

CREATE INDEX companies_company_symbol_9f158f8c_like ON public.companies_company USING btree (symbol varchar_pattern_ops);


--
-- Name: companies_dailyprice_company_id_f522c76a; Type: INDEX; Schema: public; Owner: nimesh
--

CREATE INDEX companies_dailyprice_company_id_f522c76a ON public.companies_dailyprice USING btree (company_id);


--
-- Name: companies_f_company_d9348b_idx; Type: INDEX; Schema: public; Owner: nimesh
--

CREATE INDEX companies_f_company_d9348b_idx ON public.companies_floorsheettransaction USING btree (company_id, date);


--
-- Name: companies_floorsheettransaction_company_id_92bd2bd9; Type: INDEX; Schema: public; Owner: nimesh
--

CREATE INDEX companies_floorsheettransaction_company_id_92bd2bd9 ON public.companies_floorsheettransaction USING btree (company_id);


--
-- Name: crawler_crawlrun_triggered_by_id_a54e1d5c; Type: INDEX; Schema: public; Owner: nimesh
--

CREATE INDEX crawler_crawlrun_triggered_by_id_a54e1d5c ON public.crawler_crawlrun USING btree (triggered_by_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: nimesh
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: nimesh
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: nimesh
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: nimesh
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: news_articlecategory_article_id_b3701557; Type: INDEX; Schema: public; Owner: nimesh
--

CREATE INDEX news_articlecategory_article_id_b3701557 ON public.news_articlecategory USING btree (article_id);


--
-- Name: news_articlecategory_company_id_9e465d24; Type: INDEX; Schema: public; Owner: nimesh
--

CREATE INDEX news_articlecategory_company_id_9e465d24 ON public.news_articlecategory USING btree (company_id);


--
-- Name: news_categorycorrection_article_category_id_9070a947; Type: INDEX; Schema: public; Owner: nimesh
--

CREATE INDEX news_categorycorrection_article_category_id_9070a947 ON public.news_categorycorrection USING btree (article_category_id);


--
-- Name: news_categorycorrection_corrected_by_id_ea6658eb; Type: INDEX; Schema: public; Owner: nimesh
--

CREATE INDEX news_categorycorrection_corrected_by_id_ea6658eb ON public.news_categorycorrection USING btree (corrected_by_id);


--
-- Name: news_categorycorrection_new_company_id_c6814ef0; Type: INDEX; Schema: public; Owner: nimesh
--

CREATE INDEX news_categorycorrection_new_company_id_c6814ef0 ON public.news_categorycorrection USING btree (new_company_id);


--
-- Name: news_categorycorrection_previous_company_id_36519e6e; Type: INDEX; Schema: public; Owner: nimesh
--

CREATE INDEX news_categorycorrection_previous_company_id_36519e6e ON public.news_categorycorrection USING btree (previous_company_id);


--
-- Name: news_rawarticle_url_17c209db_like; Type: INDEX; Schema: public; Owner: nimesh
--

CREATE INDEX news_rawarticle_url_17c209db_like ON public.news_rawarticle USING btree (url varchar_pattern_ops);


--
-- Name: analysis_behaviorsummary analysis_behaviorsum_company_id_ac7ed932_fk_companies; Type: FK CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.analysis_behaviorsummary
    ADD CONSTRAINT analysis_behaviorsum_company_id_ac7ed932_fk_companies FOREIGN KEY (company_id) REFERENCES public.companies_company(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: analysis_newspricecorrelation analysis_newspriceco_company_id_40723770_fk_companies; Type: FK CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.analysis_newspricecorrelation
    ADD CONSTRAINT analysis_newspriceco_company_id_40723770_fk_companies FOREIGN KEY (company_id) REFERENCES public.companies_company(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: companies_companyembedding companies_companyemb_company_id_c5beacea_fk_companies; Type: FK CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.companies_companyembedding
    ADD CONSTRAINT companies_companyemb_company_id_c5beacea_fk_companies FOREIGN KEY (company_id) REFERENCES public.companies_company(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: companies_dailyprice companies_dailyprice_company_id_f522c76a_fk_companies; Type: FK CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.companies_dailyprice
    ADD CONSTRAINT companies_dailyprice_company_id_f522c76a_fk_companies FOREIGN KEY (company_id) REFERENCES public.companies_company(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: companies_floorsheettransaction companies_floorsheet_company_id_92bd2bd9_fk_companies; Type: FK CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.companies_floorsheettransaction
    ADD CONSTRAINT companies_floorsheet_company_id_92bd2bd9_fk_companies FOREIGN KEY (company_id) REFERENCES public.companies_company(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: crawler_crawlrun crawler_crawlrun_triggered_by_id_a54e1d5c_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.crawler_crawlrun
    ADD CONSTRAINT crawler_crawlrun_triggered_by_id_a54e1d5c_fk_auth_user_id FOREIGN KEY (triggered_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: news_articlecategory news_articlecategory_article_id_b3701557_fk_news_rawarticle_id; Type: FK CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.news_articlecategory
    ADD CONSTRAINT news_articlecategory_article_id_b3701557_fk_news_rawarticle_id FOREIGN KEY (article_id) REFERENCES public.news_rawarticle(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: news_articlecategory news_articlecategory_company_id_9e465d24_fk_companies; Type: FK CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.news_articlecategory
    ADD CONSTRAINT news_articlecategory_company_id_9e465d24_fk_companies FOREIGN KEY (company_id) REFERENCES public.companies_company(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: news_articleembedding news_articleembedding_article_id_1510fca5_fk_news_rawarticle_id; Type: FK CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.news_articleembedding
    ADD CONSTRAINT news_articleembedding_article_id_1510fca5_fk_news_rawarticle_id FOREIGN KEY (article_id) REFERENCES public.news_rawarticle(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: news_categorycorrection news_categorycorrect_article_category_id_9070a947_fk_news_arti; Type: FK CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.news_categorycorrection
    ADD CONSTRAINT news_categorycorrect_article_category_id_9070a947_fk_news_arti FOREIGN KEY (article_category_id) REFERENCES public.news_articlecategory(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: news_categorycorrection news_categorycorrect_corrected_by_id_ea6658eb_fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.news_categorycorrection
    ADD CONSTRAINT news_categorycorrect_corrected_by_id_ea6658eb_fk_auth_user FOREIGN KEY (corrected_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: news_categorycorrection news_categorycorrect_new_company_id_c6814ef0_fk_companies; Type: FK CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.news_categorycorrection
    ADD CONSTRAINT news_categorycorrect_new_company_id_c6814ef0_fk_companies FOREIGN KEY (new_company_id) REFERENCES public.companies_company(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: news_categorycorrection news_categorycorrect_previous_company_id_36519e6e_fk_companies; Type: FK CONSTRAINT; Schema: public; Owner: nimesh
--

ALTER TABLE ONLY public.news_categorycorrection
    ADD CONSTRAINT news_categorycorrect_previous_company_id_36519e6e_fk_companies FOREIGN KEY (previous_company_id) REFERENCES public.companies_company(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict tbf2HxWq3yTV2RvnvjWaSbADXbYiAs90n3RYzodmqkKWd3r8hBqtrdT0Ja3D0Ht

