# Generated by Django 5.2.17 on 2026-08-10 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPriceCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateField()),
                ('window_end', models.DateField()),
                ('correlation_coefficient', models.FloatField()),
                ('news_count', models.IntegerField()),
                ('price_change_pct', models.FloatField()),
                ('volume_change_pct', models.FloatField()),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_correlations', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='BehaviorSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vwap', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pressure_indicator', models.CharField(choices=[('accumulation', 'Accumulation'), ('distribution', 'Distribution'), ('weak_rally', 'Weak rally'), ('weak_selloff', 'Weak selloff'), ('neutral', 'Neutral')], max_length=20)),
                ('is_volume_anomaly', models.BooleanField(default=False)),
                ('avg_volume_20d', models.BigIntegerField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_summaries', to='companies.company')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('company', 'date')},
            },
        ),
    ]
