# Generated by Django 5.2.17 on 2026-08-10 15:00

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_portal', models.CharField(max_length=50)),
                ('headline', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('method', models.CharField(choices=[('embedding', 'Embedding similarity'), ('manual', 'Manual')], default='hybrid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_categories', to='companies.company')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='news.rawarticle')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
                ('article_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='news.articlecategory')),
                ('corrected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('new_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='companies.company')),
                ('previous_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('source_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='news.rawarticle')),
            ],
        ),
        migrations.AddConstraint(
            model_name='articlecategory',
            constraint=models.UniqueConstraint(fields=('article', 'company'), name='unique_article_company_category'),
        ),
    ]
