# Generated by Django 5.2.17 on 2026-08-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='method',
            field=models.CharField(choices=[('embedding', 'Embedding similarity'), ('manual', 'Manual')], default='embedding', max_length=20),
        ),
        migrations.AlterField(
            model_name='rawarticle',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
